**Objective:**
* Employ SVM from scikit learn for binary classification.
* Impact of preprocessing data and hyper paramter search using grid search.

**1. Load the data from “college.csv” that has attributes collected about private and public colleges for a particular year. We will try to predict the private/public status of the college from other attributes**

In [56]:
import numpy as np # linear algebra
import pandas as pd # data processing

#Visualisation frameworks
import matplotlib.pyplot as plt
%matplotlib inline  
import seaborn as sns

#Tools
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [57]:
df = pd.read_csv('C:/Users/gabri/Desktop/Data Science/Python/Python for Data Science - Edureka/Module 9 - Supervised Learning 2/College.csv')
print(df.shape)
df.head()

(777, 18)

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

Let's format our target variable:
* Yes = 1;
* No = 0.

In [58]:
df.Private.unique()

array(['Yes', 'No'], dtype=object)

In [59]:
df['Private'] = df['Private'].replace('Yes', 1)
df['Private'] = df['Private'].replace('No', 0)
print(df['Private'].unique())
df.head()

[1 0]

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,1,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,1,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,1,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,1,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,1,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Private      777 non-null    int64
 1   Apps         777 non-null    int64
 2   Accept       777 non-null    int64
 3   Enroll       777 non-null    int64
 4   Top10perc    777 non-null    int64
 5   Top25perc    777 non-null    int64
 6   F.Undergrad  777 non-null    int64
 7   P.Undergrad  777 non-null    int64
 8   Outstate     777 non-null    int64
 9   Room.Board   777 non-null    int64
 10  Books        777 non-null    int64
 11  Personal     777 non-null    int64
 12  PhD          777 non-null    int64
 13  Terminal     777 non-null    int64
 14  S.F.Ratio    777 non-null    float64
 15  perc.alumni  777 non-null    int64
 16  Expend       777 non-null    int64
 17  Grad.Rate    777 non-null    int64
dtypes: float64(1), int64(17)
memory usage: 109.4 KB

In [61]:
df.isna().sum()

Private        0
Apps           0
Accept         0
Enroll         0
Top10perc      0
Top25perc      0
F.Undergrad    0
P.Undergrad    0
Outstate       0
Room.Board     0
Books          0
Personal       0
PhD            0
Terminal       0
S.F.Ratio      0
perc.alumni    0
Expend         0
Grad.Rate      0
dtype: int64

**2. Use LabelEncoder to encode the target variable in to numerical form and split the data such that 20% of the data is set aside fortesting.**

In [62]:
#As we already enconded manually due low number of values, let's just split the data
X = df.drop('Private',axis=1)
y = df['Private']

X.head()

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

In [63]:
# Split into train/test
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.2, stratify=y,
                     random_state=0)

print('X_train shape:', X_train.shape, '\nX_test shape:', X_test.shape)

X_train shape: (621, 17)
X_test shape: (156, 17)

**3. Fit a linear svm from scikit learn and observe the accuracy. [Hint:Use Linear SVC]**

In [64]:
from sklearn.svm import LinearSVC

In [65]:
model = LinearSVC(random_state=0)
model.fit(X_train,y_train)
# Predict the value of the digit on the test subset
predicted = model.predict(X_test)

print(f"Classification report for classifier {model}:\n"
      f"{metrics.classification_report(y_test, predicted)}\n")

Classification report for classifier LinearSVC(random_state=0):
              precision    recall  f1-score   support

           0       0.87      0.77      0.81        43
           1       0.92      0.96      0.94       113

    accuracy                           0.90       156
   macro avg       0.89      0.86      0.87       156
weighted avg       0.90      0.90      0.90       156

C:\Users\gabri\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

**4. Preprocess the data using StandardScalar and fit the same model again and observe the change in accuracy.**

In [66]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [67]:
model2 = make_pipeline(StandardScaler(),
                         LinearSVC(random_state=0))

model2.fit(X_train, y_train)

C:\Users\gabri\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC(random_state=0))])

In [68]:
predicted2 = model2.predict(X_test)

In [69]:
print(f"Classification report for classifier {model2}:\n"
      f"{metrics.classification_report(y_test, predicted2)}\n")

Classification report for classifier Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC(random_state=0))]):
              precision    recall  f1-score   support

           0       0.86      0.84      0.85        43
           1       0.94      0.95      0.94       113

    accuracy                           0.92       156
   macro avg       0.90      0.89      0.89       156
weighted avg       0.92      0.92      0.92       156

**5. Use scikit learn’s gridsearch to select the best hyperparameter for a non-linear SVM,identify the model with best score and its parameters.**

In [70]:
from sklearn.svm import SVC

In [71]:
model3 = make_pipeline(StandardScaler(), SVC())

model3.fit(X_train, y_train)

predicted3 = model3.predict(X_test)

print(f"Classification report for classifier {model3}:\n"
      f"{metrics.classification_report(y_test, predicted3)}\n")

Classification report for classifier Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())]):
              precision    recall  f1-score   support

           0       0.86      0.84      0.85        43
           1       0.94      0.95      0.94       113

    accuracy                           0.92       156
   macro avg       0.90      0.89      0.89       156
weighted avg       0.92      0.92      0.92       156

Let's use a more sophisticated technique so it doesn't take too long:

In [99]:
from skopt import forest_minimize
from sklearn.model_selection import cross_val_score

In [100]:
def tune_xgbr(params):

    
    C = params[0] 
    gamma = params[1] 

    print(params, '\n')
    #Model to be optimized
    mdl = make_pipeline(StandardScaler(), SVC(C=C,gamma=gamma))

    #Cross-Validation in order to avoid overfitting
    mse = cross_val_score(mdl, X_train, y_train, cv = 5, scoring = 'neg_mean_squared_error')
    mse = (-mse)
    print(mse.mean())
    return mse.mean()

In [102]:
# Creating a sample space in which the initial randomic search should be performed
param_grid = [(0.01, 1), # C
          (0.1, 5)] # gamma
              
# Minimization using a random forest with 10 random samples and 40  iterations for forest minimize optimization.
result = forest_minimize(tune_xgbr, param_grid, random_state=1, n_calls=50, n_initial_points=10, n_jobs=-1, verbose=3)

Iteration No: 1 started. Evaluating function at random point.
[0.99721296282948, 4.669531060759429]

0.27214193548387094
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.1606
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 2 started. Evaluating function at random point.
[0.13684320345006318, 4.99529852508831]

0.27214193548387094
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.1426
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 3 started. Evaluating function at random point.
[0.24372808718245634, 2.0432455637505282]

0.27214193548387094
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.1466
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 4 started. Evaluating function at random point.
[0.3940316337503874, 3.3817555803370527]

0.27214193548387094
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.1521
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 5 started. Evaluating function at random point.
[0.9361836800979716, 4.246923491761485]

0.27214193548387094
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.1486
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 6 started. Evaluating function at random point.
[0.3201407817629524, 2.6702859819070706]

0.27214193548387094
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.1815
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 7 started. Evaluating function at random point.
[0.44901836484176116, 1.2249283472761454]

0.27214193548387094
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.1696
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 8 started. Evaluating function at random point.
[0.539069769857547, 4.578413920438242]

0.27214193548387094
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.1496
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 9 started. Evaluating function at random point.
[0.46263275990711844, 2.210422979205072]

0.27214193548387094
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.1436
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 10 started. Evaluating function at random point.
[0.9397365115293895, 3.914107258049015]

0.27214193548387094
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.5347
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 11 started. Searching for the next optimal point.
[0.7188108108086807, 1.456579743149113]

0.27214193548387094
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.4618
Function value obtained: 0.2721
Current minimum: 0.2721
Iteration No: 12 started. Searching for the next optimal point.
[0.8030361514075414, 0.5743102058075682]

0.20619354838709678
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.4589
Function value obtained: 0.2062
Current minimum: 0.2062
Iteration No: 13 started. Searching for the next optimal point.
[0.8043177249512521, 1.2228525868558122]

0.27214193548387094
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.4699
Function value obtained: 0.2721
Current minimum: 0.2062
Iteration No: 14 started. Searching for the next optimal point.
[0.8051565929724842, 0.5679018720095677]

0.20458064516129032
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.4566
Function value obtained: 0.2046
Current minimum: 0.2046
Iteration No: 15 started. Searching for the next optimal point.
[0.8039133360883404, 0.13408289343037472]

0.0628258064516129
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.4176
Function value obtained: 0.0628
Current minimum: 0.0628
Iteration No: 16 started. Searching for the next optimal point.
[0.7944304496428464, 0.42774094180122924]

0.15781935483870965
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.5096
Function value obtained: 0.1578
Current minimum: 0.0628
Iteration No: 17 started. Searching for the next optimal point.
[0.806418990183608, 0.5368248093027737]

0.19167741935483873
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.4715
Function value obtained: 0.1917
Current minimum: 0.0628
Iteration No: 18 started. Searching for the next optimal point.
[0.799399987276277, 0.2851994153006131]

0.11433548387096774
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.4379
Function value obtained: 0.1143
Current minimum: 0.0628
Iteration No: 19 started. Searching for the next optimal point.
[0.8152908215116971, 0.14872516859633383]

0.06281290322580645
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.4188
Function value obtained: 0.0628
Current minimum: 0.0628
Iteration No: 20 started. Searching for the next optimal point.
[0.8631145199233998, 0.24991158181747802]

0.09178064516129034
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.4287
Function value obtained: 0.0918
Current minimum: 0.0628
Iteration No: 21 started. Searching for the next optimal point.
[0.8829892884285007, 0.13545704935750708]

0.0628258064516129
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.4358
Function value obtained: 0.0628
Current minimum: 0.0628
Iteration No: 22 started. Searching for the next optimal point.
[0.9855985227769825, 0.14506795635810024]

0.061212903225806456
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.4400
Function value obtained: 0.0612
Current minimum: 0.0612
Iteration No: 23 started. Searching for the next optimal point.
[0.9333379263756906, 0.14418579284813499]

0.061212903225806456
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.4424
Function value obtained: 0.0612
Current minimum: 0.0612
Iteration No: 24 started. Searching for the next optimal point.
[0.9815751068162841, 0.11226902790119282]

0.05476129032258065
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.5009
Function value obtained: 0.0548
Current minimum: 0.0548
Iteration No: 25 started. Searching for the next optimal point.
[0.980953806297536, 0.14500239995600167]

0.061212903225806456
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.4856
Function value obtained: 0.0612
Current minimum: 0.0548
Iteration No: 26 started. Searching for the next optimal point.
[0.9685119293104748, 0.2136232837279294]

0.08051612903225806
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.4745
Function value obtained: 0.0805
Current minimum: 0.0548
Iteration No: 27 started. Searching for the next optimal point.
[0.6849297390737511, 0.11100704063248058]

0.06601290322580645
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.4688
Function value obtained: 0.0660
Current minimum: 0.0548
Iteration No: 28 started. Searching for the next optimal point.
[0.646628959751752, 0.12072350376384845]

0.06923870967741935
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.4310
Function value obtained: 0.0692
Current minimum: 0.0548
Iteration No: 29 started. Searching for the next optimal point.
[0.5472247372820654, 0.10737773583327358]

0.0676258064516129
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.4248
Function value obtained: 0.0676
Current minimum: 0.0548
Iteration No: 30 started. Searching for the next optimal point.
[0.4940987779215017, 0.11304237689593333]

0.07083870967741936
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.4246
Function value obtained: 0.0708
Current minimum: 0.0548
Iteration No: 31 started. Searching for the next optimal point.
[0.27141380160144124, 0.10291412865555537]

0.08534193548387095
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.4318
Function value obtained: 0.0853
Current minimum: 0.0548
Iteration No: 32 started. Searching for the next optimal point.
[0.03870037264706833, 0.14073970127161783]

0.27214193548387094

Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.4595
Function value obtained: 0.2721
Current minimum: 0.0548
Iteration No: 33 started. Searching for the next optimal point.
[0.6345362698736253, 0.13959880455018336]

0.0692258064516129
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.4592
Function value obtained: 0.0692
Current minimum: 0.0548
Iteration No: 34 started. Searching for the next optimal point.
[0.6535825534926445, 0.13924806164478293]

0.0676258064516129
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.4397
Function value obtained: 0.0676
Current minimum: 0.0548
Iteration No: 35 started. Searching for the next optimal point.
[0.5199877119524059, 0.1371180986297055]

0.0724516129032258
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.4429
Function value obtained: 0.0725
Current minimum: 0.0548
Iteration No: 36 started. Searching for the next optimal point.
[0.5406806270302196, 0.13542619603732284]

0.0724516129032258
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.4410
Function value obtained: 0.0725
Current minimum: 0.0548
Iteration No: 37 started. Searching for the next optimal point.
[0.4768977645625167, 0.13536237134172097]

0.0772774193548387
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.4174
Function value obtained: 0.0773
Current minimum: 0.0548
Iteration No: 38 started. Searching for the next optimal point.
[0.44290675154756803, 0.14155942057241105]

0.07889032258064516
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.4220
Function value obtained: 0.0789
Current minimum: 0.0548
Iteration No: 39 started. Searching for the next optimal point.
[0.22593912490173496, 0.1120866152512171]

0.09984516129032259
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.4215
Function value obtained: 0.0998
Current minimum: 0.0548
Iteration No: 40 started. Searching for the next optimal point.
[0.3963833356425826, 0.1408586125113685]

0.08532903225806451
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.4373
Function value obtained: 0.0853
Current minimum: 0.0548
Iteration No: 41 started. Searching for the next optimal point.
[0.38085947992201086, 0.1445500034553264]

0.08855483870967742
Iteration No: 41 ended. Search finished for the next optimal point.
Time taken: 0.4560
Function value obtained: 0.0886
Current minimum: 0.0548
Iteration No: 42 started. Searching for the next optimal point.
[0.3127858067364145, 0.13369948508307522]

0.09500645161290322
Iteration No: 42 ended. Search finished for the next optimal point.
Time taken: 0.4271
Function value obtained: 0.0950
Current minimum: 0.0548
Iteration No: 43 started. Searching for the next optimal point.
[0.6909148502605006, 0.14034916991730448]

0.06441290322580645
Iteration No: 43 ended. Search finished for the next optimal point.
Time taken: 0.4509
Function value obtained: 0.0644
Current minimum: 0.0548
Iteration No: 44 started. Searching for the next optimal point.
[0.7244152140366895, 0.13051107604977502]

0.0644258064516129
Iteration No: 44 ended. Search finished for the next optimal point.
Time taken: 0.4518
Function value obtained: 0.0644
Current minimum: 0.0548
Iteration No: 45 started. Searching for the next optimal point.
[0.27722268108773884, 0.1411757848608451]

0.10145806451612904
Iteration No: 45 ended. Search finished for the next optimal point.
Time taken: 0.4537
Function value obtained: 0.1015
Current minimum: 0.0548
Iteration No: 46 started. Searching for the next optimal point.
[0.7148338414743317, 0.14372530468748174]

0.06441290322580645
Iteration No: 46 ended. Search finished for the next optimal point.
Time taken: 0.4377
Function value obtained: 0.0644
Current minimum: 0.0548
Iteration No: 47 started. Searching for the next optimal point.
[0.7189518273770517, 0.1387397876701928]

0.06441290322580645
Iteration No: 47 ended. Search finished for the next optimal point.
Time taken: 0.4361
Function value obtained: 0.0644
Current minimum: 0.0548
Iteration No: 48 started. Searching for the next optimal point.
[0.4720650806028174, 0.2037914976559713]

0.1078967741935484
Iteration No: 48 ended. Search finished for the next optimal point.
Time taken: 0.4437
Function value obtained: 0.1079
Current minimum: 0.0548
Iteration No: 49 started. Searching for the next optimal point.
[0.756969382447854, 0.13307131023549962]

0.06281290322580645
Iteration No: 49 ended. Search finished for the next optimal point.
Time taken: 0.4431
Function value obtained: 0.0628
Current minimum: 0.0548
Iteration No: 50 started. Searching for the next optimal point.
[0.9454558377399542, 0.11527368407745898]

0.056374193548387096
Iteration No: 50 ended. Search finished for the next optimal point.
Time taken: 0.4617
Function value obtained: 0.0564
Current minimum: 0.0548

In [104]:
model3 = make_pipeline(StandardScaler(), SVC(C=0.981, gamma=0.145))

model3.fit(X_train, y_train)

predicted3 = model3.predict(X_test)

print(f"Classification report for classifier {model3}:\n"
      f"{metrics.classification_report(y_test, predicted3)}\n")

Classification report for classifier Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(C=0.981, gamma=0.145))]):
              precision    recall  f1-score   support

           0       0.88      0.86      0.87        43
           1       0.95      0.96      0.95       113

    accuracy                           0.93       156
   macro avg       0.91      0.91      0.91       156
weighted avg       0.93      0.93      0.93       156

Okay! We got better results with a few lines of code.